services:
  miner-monitor:
    build: .
    container_name: miner-monitor
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./miners.yaml:/config/miners.yaml:ro
      - ./.env:/config/.env:ro
    environment:
      - TZ=Europe/Berlin
